[package]
name = "grafik-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Grafik components for native GPUI interfaces."

[dependencies]
gpui.workspace = true
grafik-motion.workspace = true
grafik-theme.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
